# Site settings
title: Kevin Liao
author: Kevin Liao
email: kliao6@illinois.edu
description: Academic homepage of Kevin Liao.
url: http://www.kevliao.com
paginate: 5

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
